@Library('jenkinsLibs') _
pipeline {
    agent {
        label 'docker-node'
    }

    stages {
        stage('docker build') {
            steps {
                script {
                    dockerLib.build(DockerfilePath: "02-primer-pipeline/Dockerfile",
                                    DockerImage: "caosbinario/homer_page:1.0.0-${env.BUILD_NUMBER}",
                                    DockerContext: "02-primer-pipeline")
                }
            }
        }
        stage('docker push') {
            steps {
                script {
                    dockerLib.push(DockerImage: "caosbinario/homer_page:1.0.0-${env.BUILD_NUMBER}")
                }
            }
        }
    }
}
